config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :compositions
  resources :kits do 
    collection do
      get :generar
      post :generar
      get :despiece
      post :despiece
      post :despiece_save
    end
  end

  resources :elements do
    collection do
      get :stock
    end
  end

  root 'elements#index'

  

end

app/models/element.rb
class Element < ActiveRecord::Base
	validates :codigo, presence: true
	validates :descripcion, presence: true
	validates :marca, presence: true
	validates :modelo, presence: true
	validates :stock, presence: true

end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  before_action :set_element, only: [:show, :edit, :update, :destroy]
  # GET /elements
  # GET /elements.json
  def index
    @elements = Element.all.paginate(page: params[:page],per_page: 10)
    @index_text = 'Lista de elementos'
    @menu_elements = true
    
  end

  # GET /elements/1
  # GET /elements/1.json
  def show
    @index_text = 'Ver elemento'
    @menu_elements = true
    
  end

  # GET /elements/new
  def new
    @index_text = 'Nuevo elemento'
    @menu_elements = true
    @element = Element.new
    
  end

  # GET /elements/1/edit
  def edit
    @index_text = 'Editar elemento'
    @menu_elements = true
    
  end

  def stock
    @index_text = 'Stock de elementos totales'
    @menu_elements_stock = true
    valid = false
    if request.params['codigo']
      if request.params['codigo'].size > 0
        valid = true
      end
    end

    if valid
      @elements = Element.where('codigo = ? ', request.params['codigo'].upcase).order(:stock).paginate(page: params[:page],per_page: 10)
    else
      @elements = Element.order(:stock).paginate(page: params[:page],per_page: 10)
    end
    for element in  @elements
      contador = 0
      compositions = Composition.where('element_id = ?', element.id)
      for  composition in compositions
        contador = contador + (composition.cantidad *  composition.kit.stock)
      end
      element.stock = contador 
    end
    
  end

  # POST /elements
  # POST /elements.json
  def create
    @element = Element.new(element_params)
    @menu_elements = true
    respond_to do |format|
      if @element.save
        format.html { redirect_to @element, notice: 'Elemento creado exitosamente.' }
        format.json { render :show, status: :created, location: @element }
      else
        format.html { render :new }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /elements/1
  # PATCH/PUT /elements/1.json
  def update
    @menu_elements = true
    respond_to do |format|
      if @element.update(element_params)
        format.html { redirect_to @element, notice: 'Elemento creado exitosamente.' }
        format.json { render :show, status: :ok, location: @element }
      else
        format.html { render :edit}
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elements/1
  # DELETE /elements/1.json
  def destroy
    @element.destroy
    @menu_elements = true
    respond_to do |format|
      format.html { redirect_to elements_url, notice: 'Elemento eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_element
      @element = Element.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def element_params
      params.require(:element).permit(:codigo, :descripcion, :marca, :modelo, :stock)
    end

    def element_search_params
      params.require(:element).permit(:codigo)
    end
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/views/elements/_form.html.erb
<%= form_for(@element, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @element.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@element.errors.count, "error") %> prohibited this element from being saved:</h4>

      <ul>
      <% @element.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :codigo, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :codigo, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :descripcion, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :descripcion, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :marca, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :marca, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :modelo, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :modelo, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :stock, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :stock, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/elements/edit.html.erb
<div class="row">
<div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">&nbsp;</h3>
        <div class="actions pull-right">
            <%= link_to elements_path, class: 'btn btn-default btn-sm' do %>
            <span class="glyphicon glyphicon-list-alt"></span>
            Atras
          <% end %>

            <%= link_to @element, class: 'btn btn-primary btn-sm' do %>
		    <span class="glyphicon glyphicon-info-sign"></span>
		    Ver
		  <% end %>
        </div>
      </div>


      <div class="panel-body">
      	<%= render 'form' %>
      </div>
  </div>
</div>

app/views/elements/index.html.erb
<div class="row">
<div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">&nbsp;</h3>
        <div class="actions pull-right">
            <%= link_to new_element_path, class: 'btn btn-primary btn-sm' do %>
            <span class="glyphicon glyphicon-plus"></span>
            Agregar
          <% end %>
        </div>
      </div>


      <div class="panel-body">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
                  <th>Codigo</th>
                  <th>Descripcion</th>
                  <th>Marca</th>
                  <th>Modelo</th>
                  <th>Stock</th>
                  <th>#</th>
                  <th></th>
                  <th></th>
            </tr>
          </thead>

          <tbody>
            <%= content_tag_for(:tr, @elements) do |element| %>
                  <td><%= element.codigo %></td>
                  <td><%= element.descripcion %></td>
                  <td><%= element.marca %></td>
                  <td><%= element.modelo %></td>
                  <td><%= element.stock %></td>
                  <td><%= link_to '', element,:class => "glyphicon glyphicon-eye-open" %></td>
              <td><%= link_to '', edit_element_path(element),:class => "glyphicon glyphicon-pencil" %></td>
              <td><%= link_to '', element, method: :delete, data: { confirm: 'Estas seguro?' },:class => "glyphicon glyphicon-remove" %></td>
            <% end %>
          </tbody>
        </table>
        <%=will_paginate @elements %>
      </div>
    </div>
  </div>
</div>

app/views/elements/new.html.erb
<div class="row">
<div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">&nbsp;</h3>
        <div class="actions pull-right">
            <%= link_to elements_path, class: 'btn btn-default btn-sm' do %>
            <span class="glyphicon glyphicon-list-alt"></span>
            Atras
          <% end %>
        </div>
      </div>


      <div class="panel-body">
      	<%= render 'form' %>
      </div>
  </div>
</div>

app/views/elements/show.html.erb
<div class="row">
<div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">&nbsp;</h3>
        <div class="actions pull-right">
            <%= link_to elements_path, class: 'btn btn-default btn-sm' do %>
            <span class="glyphicon glyphicon-list-alt"></span>
            Atras
          <% end %>

            <%= link_to edit_element_path(@element), class: 'btn btn-primary btn-sm' do %>
            <span class="glyphicon glyphicon-pencil"></span>
            Editar
          <% end %>
        </div>
      </div>


      <div class="panel-body">
        <dl class="dl-horizontal">
        <dt>Codigo:</dt>
        <dd><%= @element.codigo %></dd>

        <dt>Descripcion:</dt>
        <dd><%= @element.descripcion %></dd>

        <dt>Marca:</dt>
        <dd><%= @element.marca %></dd>

        <dt>Modelo:</dt>
        <dd><%= @element.modelo %></dd>

        <dt>Stock:</dt>
        <dd><%= @element.stock %></dd>

      </dl>
      </div>
  </div>
</div>





<!-- <div class="page-header">
  <%= link_to elements_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_element_path(@element), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show element</h1>
</div>

<dl class="dl-horizontal">
  <dt>Codigo:</dt>
  <dd><%= @element.codigo %></dd>

  <dt>Descripcion:</dt>
  <dd><%= @element.descripcion %></dd>

  <dt>Marca:</dt>
  <dd><%= @element.marca %></dd>

  <dt>Modelo:</dt>
  <dd><%= @element.modelo %></dd>

  <dt>Stock:</dt>
  <dd><%= @element.stock %></dd>

</dl> -->

app/views/elements/stock.html.erb
<div class="row">
<div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <form role="form" class="form-inline" method="GET">
          
          <div class="form-group">
          <label for="exampleInputPassword2" style="padding-top: 0.5em;" class="col-sm-6">Codigo elemento:</label>
          <div class="col-sm-4">
          <input type="text" name="codigo" placeholder="codigo"  class="form-control" >
          </div>
          </div>
          <button class="btn btn-white" style="margin-top: 0.5em;" type="submit">Buscar</button>

        </form>
      </div>

      <div class="panel-body">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
                  <th>Codigo</th>
                  <th>Descripcion</th>
                  <th>Marca</th>
                  <th>Modelo</th>
                  <th>Stock</th>
            </tr>
          </thead>

          <tbody>
            <%= content_tag_for(:tr, @elements) do |element| %>
                  <td><%= element.codigo %></td>
                  <td><%= element.descripcion %></td>
                  <td><%= element.marca %></td>
                  <td><%= element.modelo %></td>
                  <td><%= element.stock %></td>
                  
            <% end %>
          </tbody>
        </table>
        <%=will_paginate @elements %>
      </div>
    </div>
  </div>
</div>