config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :compositions
  resources :kits do 
    collection do
      get :generar
      post :generar
      get :despiece
      post :despiece
      post :despiece_save
    end
  end

  resources :elements do
    collection do
      get :stock
    end
  end

  root 'elements#index'

  

end

app/models/composition.rb
class Composition < ActiveRecord::Base
  belongs_to :kit
  belongs_to :element
  validates :cantidad, presence: true
  validates :kit, presence: true
  validates :element, presence: true
end

app/controllers/compositions_controller.rb
class CompositionsController < ApplicationController
  before_action :set_composition, only: [:show, :edit, :update, :destroy],authenticate_user!:
  
  #:authenticate_user!,
  # GET /compositions
  # GET /compositions.json
  def index
    @compositions = Composition.all.paginate(page: params[:page],per_page: 10)
    
  end

  # GET /compositions/1
  # GET /compositions/1.json
  def show
    
  end

  # GET /compositions/new
  def new
    @composition = Composition.new
    
  end

  # GET /compositions/1/edit
  def edit
    
  end


  # POST /compositions
  # POST /compositions.json
  def create
    @composition = Composition.new(composition_params)

    respond_to do |format|
      if @composition.save
        format.html { redirect_to @composition, notice: 'Composicion creada exitosamente.' }
        format.json { render :show, status: :created, location: @composition }
      else
        format.html { render :new }
        format.json { render json: @composition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compositions/1
  # PATCH/PUT /compositions/1.json
  def update
    respond_to do |format|
      if @composition.update(composition_params)
        format.html { redirect_to @composition, notice: 'Composicion actualizada correctamente.' }
        format.json { render :show, status: :ok, location: @composition }
      else
        format.html { render :edit }
        format.json { render json: @composition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compositions/1
  # DELETE /compositions/1.json
  def destroy
    @composition.destroy
    respond_to do |format|
      format.html { redirect_to compositions_url, notice: 'Composicion eliminada correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_composition
      @composition = Composition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def composition_params
      params.require(:composition).permit(:cantidad, :kit_id, :element_id)
    end
end

app/helpers/compositions_helper.rb
module CompositionsHelper
end

app/views/compositions/_form.html.erb
<%= form_for(@composition, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @composition.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@composition.errors.count, "error") %> prohibited this composition from being saved:</h4>

      <ul>
      <% @composition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :cantidad, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :cantidad, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :kit, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select :kit_id, Kit.all, :id, :codigo , {}, {:class=> 'form-control'} %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :element, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.collection_select :element_id, Element.all, :id ,:codigo,{}, {:class=> 'form-control'}  %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/compositions/edit.html.erb
<div class="page-header">
  <%= link_to compositions_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @composition, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing composition</h1>
</div>

<%= render 'form' %>

app/views/compositions/index.html.erb
<div class="row">
<div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">&nbsp;</h3>
        <div class="actions pull-right">
            <%= link_to new_composition_path, class: 'btn btn-primary btn-sm' do %>
            <span class="glyphicon glyphicon-plus"></span>
            Nuevo
          <% end %>
        </div>
      </div>


      <div class="panel-body">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
                  <th>Cantidad</th>
                  <th>Kit</th>
                  <th>Element</th>
                  <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <%= content_tag_for(:tr, @compositions) do |composition| %>
                  <td><%= composition.cantidad %></td>
                  <td><%= composition.kit.codigo %></td>
                  <td><%= composition.element.codigo %></td>
                  <td><%= link_to '', composition ,:class => "glyphicon glyphicon-eye-open"%></td>
              <td><%= link_to '', edit_composition_path(composition),:class => "glyphicon glyphicon-pencil" %></td>
              <td><%= link_to '', composition, method: :delete, data: { confirm: 'Estas seguro?' },:class => "glyphicon glyphicon-remove" %></td>
            <% end %>
          </tbody>
        </table>
        <%=will_paginate @compositions %>
      </div>
    </div>
  </div>
</div>

app/views/compositions/new.html.erb
<div class="page-header">
  <%= link_to compositions_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New composition</h1>
</div>

<%= render 'form' %>

app/views/compositions/show.html.erb
<div class="page-header">
  <%= link_to compositions_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_composition_path(@composition), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show composition</h1>
</div>

<dl class="dl-horizontal">
  <dt>Cantidad:</dt>
  <dd><%= @composition.cantidad %></dd>

  <dt>Kit:</dt>
  <dd><%= @composition.kit.codigo %></dd>

  <dt>Element:</dt>
  <dd><%= @composition.element.codigo %></dd>

</dl>